#include <string>
#include "Credits.h"

namespace Shiro {
    namespace Credits {
        std::string creditsString =
            "#STAFF\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "#GAME DESIGN\n"
            "\n"
            "Felicity Violette\n"
            "\n"
            "\n"
            "\n"
            "#GITHUB\n"
            "#CONTRIBUTORS\n"
            "\n"
            "ericjtaylor\n"
            "\n"
            "FelicityVi\n"
            "\n"
            "kdex\n"
            "\n"
            "MaryHal\n"
            "\n"
            "nightmareci\n"
            "\n"
            "PARTYMANX\n"
            "\n"
            "raincomplex\n"
            "\n"
            "sinefuse\n"
            "\n"
            "that1\n"
            "\n"
            "zeamador\n"
            "\n"
            "\n"
            "\n"
            "#MUSIC\n"
            "\n"
            "beach glass\n"
            "\n"
            "Ian Walker\n"
            "\n"
            "Robert Kooima\n"
            "\n"
            "\n"
            "\n"
            "#SOUND EFFECTS\n"
            "\n"
            "beach glass\n"
            "\n"
            "Damian Yerrick\n"
            "\n"
            "\n"
            "\n"
            "#VISUAL DESIGN\n"
            "\n"
            "Felicity Violette\n"
            "\n"
            "\n"
            "\n"
            "#SPECIAL THANKS\n"
            "\n"
            "raincomplex\n"
            "\n"
            "that1\n"
            "\n"
            "Mihara-san and\n"
            "everyone at ARIKA";
    }
}