// internal name, relative filename

IMG(title, "title")
IMG(title_emboss, "title_emboss")
IMG(tetrion_qs_white, "tetrion_qs_white")
IMG(tets_bright_qs, "tets_bright_qs")
IMG(tets_bright_qs_small, "tets_bright_qs_small")
IMG(tets_dark_qs, "tets_dark_qs")
IMG(tets_jeweled, "tets_jeweled")
IMG(playfield_grid, "playfield_grid")
IMG(playfield_grid_alt, "playfield_grid_alt")
IMG(font, "font")
IMG(font_no_outline, "font_no_outline")
IMG(font_outline_only, "font_outline_only")
IMG(font_square_no_outline, "font_square_no_outline")
IMG(font_square_outline_only, "font_square_outline_only")
IMG(font_thin, "font_thin")
IMG(font_thin_no_outline, "font_thin_no_outline")
IMG(font_thin_outline_only, "font_thin_outline_only")
IMG(font_small, "font_small")
IMG(font_tiny, "font_tiny")
IMG(font_fixedsys_excelsior, "font_fixedsys_excelsior")
IMG(misc, "misc")
// the backgrounds must be adjacent and in order because they are addressed by offset:
IMG(bg0, "bg0")
IMG(bg1, "bg1")
IMG(bg2, "bg2")
IMG(bg3, "bg3")
IMG(bg4, "bg4")
IMG(bg5, "bg5")
IMG(bg6, "bg6")
IMG(bg7, "bg7")
IMG(bg8, "bg8")
IMG(bg9, "bg9")
IMG(bg10, "bg10")
IMG(bg11, "bg11")
IMG(bg12, "bg12")
IMG(bg_temp, "bg-temp")
IMG(bg_darken, "bg_darken")
IMG(medals, "medals")

// the frames must be adjacent and in order because they are addressed by offset:
IMG(animation_lineclear0, "animation/lineclear0")
IMG(animation_lineclear1, "animation/lineclear1")
IMG(animation_lineclear2, "animation/lineclear2")
IMG(animation_lineclear3, "animation/lineclear3")
IMG(animation_lineclear4, "animation/lineclear4")

IMG(g1_tetrion_g1, "g1/tetrion_g1")

//IMG(g2_tets_bright_g2, "g2/tets_bright_g2")
//IMG(g2_tets_bright_g2_small, "g2/tets_bright_g2_small")
//IMG(g2_tets_dark_g2, "g2/tets_dark_g2")
IMG(g2_tetrion_g2_death, "g2/tetrion_g2_death")
IMG(g2_tetrion_g2_master, "g2/tetrion_g2_master")

IMG(g3_tetrion_g3_terror, "g3/tetrion_g3_terror")
