jobs:
  x64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq build-essential cmake coreutils gcc libc++-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libvorbis-dev libsqlite3-dev
    - name: Build targets
      run: .github/workflows/build ${{ matrix.build-type }} ${{ matrix.compiler }}
    - name: Run Catch2 tests
      run: ./build/tests --reporter compact
    strategy:
      matrix:
        compiler:
          - clang++
          - g++
        build-type:
          - Debug
          - Release
  x64-mac-os:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install mac OS dependencies
      run: brew install bash cmake gcc libvorbis pkg-config sdl2 sdl2_image sdl2_mixer
    - name: Build targets
      run: .github/workflows/build ${{ matrix.build-type }} ${{ matrix.compiler }}
    - name: Run Catch2 tests
      run: ./build/tests --reporter compact
    strategy:
      matrix:
        compiler:
          - clang++
          - g++
        build-type:
          - Debug
          - Release
  x64-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_mixer
          mingw-w64-x86_64-sqlite3
          mingw-w64-x86_64-dlfcn
    - name: Build targets
      run: .github/workflows/build ${{ matrix.build-type }} ${{ matrix.compiler }}
      shell: msys2 {0}
    - name: Build artifact tree
      run: |
        mkdir artifacts
        for DLL in $(ldd build/shiromino.exe | grep -v '/c/' | cut -d " " -f 3); do cp $DLL artifacts; done
        mv build/shiromino.exe data LICENSE.md README.md shiromino.ini artifacts
      shell: msys2 {0}
    - name: Run Catch2 tests
      run: ./build/tests --reporter compact
      shell: msys2 {0}
    - if: matrix.build-type == 'Release' && matrix.compiler == 'clang++'
      name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: shiromino-windows-x64-${{ github.sha }}
        path: artifacts/*
    strategy:
      matrix:
        build-type:
          - Debug
          - Release
        compiler:
          - clang++
          - g++
  deploy-aur-package:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - x64-linux
      - x64-mac-os
      - x64-windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fetch history for all tags
      run: .github/workflows/fetch-tags
    - run: echo "VERSION=$(git describe --tags | tr - +)" >> $GITHUB_ENV
    - name: Archive repository
      run: git archive --prefix="${{ github.event.repository.name }}-$VERSION/" -o "${{ github.event.repository.name }}-$VERSION.tar.gz" "$VERSION"
    - name: Set archive checksum
      run: echo "CHECKSUM=$(sha256sum "${{ github.event.repository.name }}-$VERSION".tar.gz | awk '{ print $1 }')" >> $GITHUB_ENV
    - run: sed "s/\$VERSION/${{ env.VERSION }}/g; s/\$CHECKSUM/${{ env.CHECKSUM }}/g" ./packages/aur/shiromino/PKGBUILD > PKGBUILD
    - uses: KSXGitHub/github-actions-deploy-aur@v2.2.4
      with:
        commit_email: shiromino+aur@github
        commit_message: Released version ${{ env.VERSION }}
        commit_username: shiromino-bot
        force_push: true
        pkgbuild: PKGBUILD
        pkgname: shiromino
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
  release:
      if: startsWith(github.ref, 'refs/tags/')
      needs:
        - x64-linux
        - x64-mac-os
        - x64-windows
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v2
        - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - run: for FILE in *; do mv $FILE ${FILE//-${{ github.sha }}}-$VERSION; done
        - run: for FILE in *; do zip -r $FILE.zip $FILE; done
        - name: Create new release
          uses: ncipollo/release-action@v1
          with:
            allowUpdates: true
            artifactErrorsFailBuild: true
            artifacts: "*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
name: build
on:
  - pull_request
  - push